name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential cmake openssh-client

    - uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.FUGUE_REGISTRY_KEY }}

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: build
      run: cargo build --features="fixed-u64" --no-default-features --verbose
